### ISSUE TITLE
[FEATURE REQUEST] Post installation commands

### ISSUE THREAD

**Issue by silvioprog** [picodotdev/alis#101]
Hi.

It would be nice some option like `POST_INSTALL_COMMANDS`. It would be useful to solve issues like https://github.com/picodotdev/alis/issues/100, for example:

```bash
POST_INSTALL_COMMANDS=("pacman -Rcns gnome-extra" "pacman -S libmicrohttpd")
```

cheers

**Comment by picodotdev** [comment]
I have doubts with this, could be useful but I dont see a good example. In my point of view the suggested POST_INSTALL_COMMANDS should not be used to undo things that the script does, in first place the script should not do that things, on other side installing custom packages is something that currently is allowed. These command examples not gives me a reason to implement it. Also I would prefer that any complex customizations maybe is better to do after installation or implemented by the script natively if are useful for anyone. But this is my opinion.

**Comment by silvioprog** [comment]
Another possible option to use with `POST_INSTALL_COMMANDS` would be execute some commands to configure the system.

**Comment by karimone** [comment]
A simple solution is: fork the repo, add a file.sh and execute it post-install.

**Comment by picodotdev** [comment]
> A simple solution is: fork the repo, add a file.sh and execute it post-install.

Yes, I think better to do this once alis reboots the system with a custom sh or any other provision tool and not within an arch-chroot.
