### ISSUE TITLE
Issue with KMS=true and nvidia (any of nvidia option)

### ISSUE THREAD

**Issue by pikachunakapika** [picodotdev/alis#104]
Very nice scripts. Thank you for your work!
It worked perfect with my intel install but nvidia failed at mkinitcpio.
I think there is a problem with order of installation:
mkinitcpio gets called before desktop_environment. Desktop environment installs the driver packages that include the modules needed for mkinitcpio for nvidia.

KMS=false and install works perfect again.

**Comment by picodotdev** [comment]
Now the display drivers are installed before mkinitcpio. Hope this fixes the issue with nvidia option.

Thanks for the report!

**Comment by pikachunakapika** [comment]
Thanks for quick update!
It works perfect after I add "display_driver" function to ALL_STEPS or it gets skipped.

Best Regards

**Comment by picodotdev** [comment]
My fault. Just fixed.
