### ISSUE TITLE
[BUG] setting shell to fish makes yay installation fail

### ISSUE THREAD

**Issue by thecakeisalie25** [picodotdev/alis#110]
I suspect this is because certain commands don't use bash, they just use whatever shell is set as the default, and in the arch-chroot that isn't a posix compatible shell. This may also be the case for things further on in the script, I don't know.

![image](https://user-images.githubusercontent.com/9502466/104726937-1d667a00-56fa-11eb-8266-6c315ae9d890.png)

**Comment by picodotdev** [comment]
Now for that rm command should be used bash instead fish. I did not tested it but should work, if you test it please confirm in a comment.
