### ISSUE TITLE
Luks kenel option for TRIM

### ISSUE THREAD

**Issue by earvingad** [picodotdev/alis#112]
According to the [archwiiki ](https://wiki.archlinux.org/index.php/Dm-crypt/Specialties#Discard/TRIM_support_for_solid_state_drives_(SSD))shouldnt the kernel option be `rd.luks.options=discard` instead of just `luks.options=discard` ?

**Comment by picodotdev** [comment]
I think that luks.options is more universal than rd.luks.options. Read the first paragraph of this [Dm-crypt](https://wiki.archlinux.org/index.php/Dm-crypt/System_configuration#Using_sd-encrypt_hook) page.

> In all of the following a rd.luks can be replaced with a luks. The rd.luks parameters are only honored by the initrd, while the luks parameters are honored by both the main system and initrd.
