### ISSUE TITLE
Failed to mount /sysroot on post-install reboot

### ISSUE THREAD

**Issue by whorider** [picodotdev/alis#114]
Sorry for the picture. I've tried install a number of times and each time I reboot, I get dropped into Emergency Mode.
I've tried various combinations, most everything is set to auto, ask, with LUKS

See Picture.

Thanks!
![pico](https://user-images.githubusercontent.com/20956397/106401175-597f2780-63e8-11eb-966f-f75da99f3d72.jpeg)

**Comment by davidgonzalez-sh** [comment]
Do you have tried the same configuration in a VirtualBox machine?

Are you installing it in a Mac?

**Comment by icedmoca** [comment]
login root account, `system ctl status sysroot.mount`

**Comment by whorider** [comment]
Thanks! I think I need to test in a vm going forward to give better log info. 

 I’ve used the script many times in the past and love it, b/c I always have trouble w/ LUKS install on manual arch installations.

I was able to get it to boot to lightDM and now I’m off and running w/ XFCE.

I am using a MacBook Air 5,2

Thanks for your work!

**Comment by picodotdev** [comment]
I did a test with this configuration https://github.com/picodotdev/alis/blob/master/packer/alis-packer-efi-ext4-luks-lvm-systemd.sh in a VirtualBox VM and the system rebooted correcty.

What you did to boot in lightDM and XFCE? If there is any need to be changed in alis leave a comment and put your alis.conf changes.

**Comment by whorider** [comment]
For some reason if finally successfully reboot post install.

I kept getting dropped to the emergency shell and could not enter any commands.

Here is my Alis.conf 
https://github.com/whorider/OSCP_Notes/blob/master/alis.conf <https://github.com/whorider/OSCP_Notes/blob/master/alis.conf>

Just in case you spot an error w/ my variables.

Thanks again, like I said, I’m up and running.

**Comment by picodotdev** [comment]
Your alis.conf seems good to me.
