### ISSUE TITLE
alis.log and alis.conf are world readable on reboot

### ISSUE THREAD

**Issue by Picea** [picodotdev/alis#115]
Hello,

During the installation alis.conf and alis.log are copied on the future root system and, on reboot, are available with too lazy permissions; everyone can read these files and so read the LUKS passphrase, root password (if it was hardcoded by user)!

During the installation, it would seem important to me to have a reminder at some point of:

1. where sensitive data like passphrases are located at the end (including USB key),
2. what the user should do to securely erase any sensitive data (shred),
3. in any case restrict the permissions to root access only.

Perhaps the installer could also propose to securely delete all the sensitive files for the user?

I wish you a good day !

**Comment by picodotdev** [comment]
Now the files owner is root and has 600 permission, also passwords are masked in log files.

Thanks for the issue.
