### ISSUE TITLE
LVM=true requires auto partition prevent use of custom partition

### ISSUE THREAD

**Issue by BigAl** [picodotdev/alis#136]
I am attempting to use custom partition with `LVM=true`

Is there any reason these for these line forces auto partitioning with using LVM ?

https://github.com/picodotdev/alis/blob/f4ccc312f72da960d29f077636319150b3a429a7/alis.sh#L139-L141

I commented them out and my custom partition install appear to go ok.

**Comment by picodotdev** [comment]
A safe ckeck. No tested that use case.

Maybe I should include this same condition 

https://github.com/picodotdev/alis/blob/f4ccc312f72da960d29f077636319150b3a429a7/alis.sh#L544

for these remove and create actions 

https://github.com/picodotdev/alis/blob/f4ccc312f72da960d29f077636319150b3a429a7/alis.sh#L581

**Comment by picodotdev** [comment]
Implemented, removed the restriction, in current state the volume group and volume logical names are not configurable (in alis.conf, should be edited alis.sh internal varaibles).
