### ISSUE TITLE
Custom repo adding

### ISSUE THREAD

**Issue by PeterDauwe** [picodotdev/alis#159]
Can a custom repo be added and where , which file would be edited to add the github adress?
Super script system , TX

**Comment by picodotdev** [comment]
See the commit changes for the how to.

**Comment by PeterDauwe** [comment]
In alis-packages.conf 
PACKAGES_PACMAN_CUSTOM_REPOSITORIES="
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs
[noobie_repo]
SigLevel = Optional TrustAll
Include = https://PeterDauwe.github.io/$repo/$arch
"

And do i add my packages as follows?
PACKAGES_PACMAN_CUSTOM="noobie-wallpaper1" in the same section

Tx for the quick response.
