### ISSUE TITLE
Can't get alis package.sh work 

### ISSUE THREAD

**Issue by Neo-29** [picodotdev/alis#168]
Everything goes well with the install but as soon as the alis package sh is launched... It ends up with nothing
As if the script didn't do the job.
I put true to the packages, tried any options.
Nothing.

**Comment by picodotdev** [comment]
Read the last echoed messages from the script maybe alis-pacakges.sh is exiting because there as some validation errors. Provide more information about the error, a photo or your alis-packages.conf file.

**Comment by Neo-29** [comment]
![Capture d’écran du 2022-01-09 23-33-16](https://user-images.githubusercontent.com/90937180/148703879-ad8bfb15-c343-4933-bf35-2310f82cd972.png)
![Capture d’écran du 2022-01-09 23-32-37](https://user-images.githubusercontent.com/90937180/148703881-fbe5295f-ead5-4e96-a45d-5d29f80c4fe2.png)

here's how it finishes

**Comment by Neo-29** [comment]
# Arch Linux Install Script (alis) configuration file
#
# Some variables values are preceded by a ! character, this means that the value is ignored.
# Some variables accept a single value others accept multiple values as annotated in the comments.
# Some variables are boolean with a value of true or false.
#
# Read the Arch Linux wiki pages to learn more about the variables values.
# https://github.com/picodotdev/alis/blob/master/README.md

# packages (all multiple)

## Arch Linux packages to install
## more at https://www.archlinux.org/packages/
## PACKAGES_PACMAN_CUSTOM_REPOSITORIES custom repositories to add to pacman configuration, see https://archlinux.org/pacman/pacman.conf.5.html#_repository_sections
### Comment lines starting with # charater are removed
PACKAGES_PACMAN_INSTALL="true"
PACKAGES_PACMAN_INSTALL_PIPEWIRE="false"
PACKAGES_PACMAN_INTERNET="!firefox chromium !curl !wget !filezilla !sshfs !openssh !transmission-gtk !transmission-qt !liferea !gnome-boxes !gnome-tweaks"
PACKAGES_PACMAN_MULTIMEDIA="!gthumb !gimp !imagemagick !krita !inkscape !blender !cmus !vlc !easytag !ardour !audacity !ffmpeg !gnome-phone-manager !kdeconnect !gstreamer !gst-plugins-good !gst-plugins-bad !gst-plugins-ugly !bluez !bluez-utils"
PACKAGES_PACMAN_UTILITIES="!bash-completion !gnome-initial-setup !gnome-extra !code !lz4 !meld !dosfstools !ntfs-3g !exfat-utils !man-db !man-pages"
PACKAGES_PACMAN_DOCUMENTS_AND_TEXT="!libreoffice-fresh !calligra !discount !lyx !vim !calibre"
PACKAGES_PACMAN_COMMUNICATION="!geary !thunderbird !empathy !kopete !polari !konversation"
PACKAGES_PACMAN_GAMES=""
PACKAGES_PACMAN_SECURITY="!ufw !rsync !gnupg !keepassxc !encfs"
PACKAGES_PACMAN_SCIENCE="!geogebra !octave"
PACKAGES_PACMAN_OTHERS="!klavaro !tmux"
PACKAGES_PACMAN_DEVELOPER="git !python !dotnet-sdk !php !rust !go !virtualbox !docker !ansible !vagrant !packer !terraform !vault !consul !nomad"
PACKAGES_PACMAN_CUSTOM=""
PACKAGES_PACMAN_PIPEWIRE="pipewire pipewire-pulse !pipewire-jack !pipewire-alsa !helvum !wireplumber !xdg-desktop-portal !xdg-desktop-portal-gnome !xdg-desktop-portal-kde !xdg-desktop-portal-wlr"
PACKAGES_PACMAN_CUSTOM_REPOSITORIES="
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs
"

## Flatpak packages to install
## more at https://flathub.org/apps/collection/popular
PACKAGES_FLATPAK_INSTALL="false"
PACKAGES_FLATPAK_INTERNET=""
PACKAGES_FLATPAK_MULTIMEDIA="!com.spotify.Client !org.ardour.Ardour !org.audacityteam.Audacity !tv.kodi.Kodi !org.pitivi.Pitivi"
PACKAGES_FLATPAK_UTILITIES="!org.freefilesync.FreeFileSync !org.gnome.World.PikaBackup !com.dropbox.Client"
PACKAGES_FLATPAK_DOCUMENTS_AND_TEXT="!org.onlyoffice.desktopeditors !com.wps.Office"
PACKAGES_FLATPAK_COMMUNICATION="!com.slack.Slack !com.microsoft.Teams !org.jitsi.jitsi-meet !us.zoom.Zoom !org.telegram.desktop"
PACKAGES_FLATPAK_GAMES="!com.valvesoftware.Steam !org.wesnoth.Wesnoth !com.albiononline.AlbionOnline !org.hedgewars.Hedgewars !com.mojang.Minecraft !net.supertuxkart.SuperTuxKart !org.openttd.OpenTTD"
PACKAGES_FLATPAK_SECURITY=""
PACKAGES_FLATPAK_SCIENCE=""
PACKAGES_FLATPAK_OTHERS="!org.gnucash.GnuCash"
PACKAGES_FLATPAK_DEVELOPER="!com.jetbrains.IntelliJ-IDEA-Community !org.eclipse.Java !com.getpostman.Postman"
PACKAGES_FLATPAK_CUSTOM=""

## SDKMAN packages to install
## more at https://sdkman.io/jdks and https://sdkman.io/sdks
PACKAGES_SDKMAN_INSTALL="false"
PACKAGES_SDKMAN_JDKS="!java !java:17.0.1-tem !java:11.0.13-tem !java:8.0.312-tem" # format <candidate>:[version]:[local-path]
PACKAGES_SDKMAN_SDKS="!gradle !maven !kotlin !groovy" # format <candidate>:[version]:[local-path]

## AUR utility and AUR packages to install
## more at https://aur.archlinux.org/packages/
PACKAGES_AUR_INSTALL="false"
PACKAGES_AUR_COMMAND="paru-bin !yay-bin !paru !yay !aurman"
PACKAGES_AUR_INTERNET=""
PACKAGES_AUR_MULTIMEDIA=""
PACKAGES_AUR_UTILITIES=""
PACKAGES_AUR_DOCUMENTS_AND_TEXT=""
PACKAGES_AUR_COMMUNICATION=""
PACKAGES_AUR_GAMES=""
PACKAGES_AUR_SECURITY=""
PACKAGES_AUR_SCIENCE=""
PACKAGES_AUR_OTHERS=""
PACKAGES_AUR_DEVELOPER=""
PACKAGES_AUR_CUSTOM=""

PACKAGES_PACMAN="$PACKAGES_PACMAN_INTERNET $PACKAGES_PACMAN_MULTIMEDIA $PACKAGES_PACMAN_UTILITIES $PACKAGES_PACMAN_DOCUMENTS_AND_TEXT $PACKAGES_PACMAN_COMMUNICATION $PACKAGES_PACMAN_GAMES $PACKAGES_PACMAN_SECURITY $PACKAGES_PACMAN_SCIENCE $PACKAGES_PACMAN_OTHERS $PACKAGES_PACMAN_DEVELOPER $PACKAGES_PACMAN_CUSTOM"
PACKAGES_FLATPAK="$PACKAGES_FLATPAK_INTERNET $PACKAGES_FLATPAK_MULTIMEDIA $PACKAGES_FLATPAK_UTILITIES $PACKAGES_FLATPAK_DOCUMENTS_AND_TEXT $PACKAGES_FLATPAK_COMMUNICATION $PACKAGES_FLATPAK_GAMES $PACKAGES_FLATPAK_SECURITY $PACKAGES_FLATPAK_SCIENCE $PACKAGES_FLATPAK_OTHERS $PACKAGES_FLATPAK_DEVELOPER $PACKAGES_FLATPAK_CUSTOM"
PACKAGES_SDKMAN="$PACKAGES_SDKMAN_JDKS $PACKAGES_SDKMAN_SDKS"
PACKAGES_AUR="$PACKAGES_AUR_INTERNET $PACKAGES_AUR_MULTIMEDIA $PACKAGES_AUR_UTILITIES $PACKAGES_AUR_DOCUMENTS_AND_TEXT $PACKAGES_AUR_COMMUNICATION $PACKAGES_AUR_GAMES $PACKAGES_AUR_SECURITY $PACKAGES_AUR_SCIENCE $PACKAGES_AUR_OTHERS $PACKAGES_AUR_DEVELOPER $PACKAGES_AUR_CUSTOM"

# systemd
## SYSTEMD_UNITS systemd units to enable or disable.
### If preceded with a "+" unit is enabled, if preceded with "-" unit is disabled, if preceded with "!" unit is ignored (no action is performed).
### eg. "+ufw.service" to enable, "-ufw.service" to disable, "!ufw.service" to ignore
SYSTEMD_UNITS="!ufw.service !bluetooth.service !docker.service"

**Comment by Neo-29** [comment]
I just enabled chromium to test
Nothimng else changes

**Comment by picodotdev** [comment]
Are you using the latest version?

A fix made in that exit point six hours ago.

https://github.com/picodotdev/alis/blob/9050b5f47d02cd30d7afcb38f35995d5964db4ba/alis-packages.sh#L210
https://github.com/picodotdev/alis/blame/9050b5f47d02cd30d7afcb38f35995d5964db4ba/alis-packages.sh#L210

**Comment by Neo-29** [comment]
Mmmmm.... My bad >>>>I clones witout checking today ...let me try that ... I'll be back

**Comment by Neo-29** [comment]
Same issue.....

**Comment by Neo-29** [comment]
Yep! Seems to be OK... Tks a lot for your support!
Excellent script!

Maybi suggest something?

Is it possible to add DisableDownloadTimeout in pacman.conf config of your script?
Indeed, I can't get the parallel download work due to my bad connection 4G box
That's something really useful ( used it tks to endeavour config)

**Comment by Neo-29** [comment]
I've got something else as issue
With aur
As I'm root on iso.. Quite logical..
Can't build
Running makepkg as root is not allowed...
An idea of the issue?

**Comment by picodotdev** [comment]
For DisableDownloadTimeout

https://github.com/picodotdev/alis/commit/709b1e747c57a9e549a5c1fc9b35fac7e82197f0

**Comment by picodotdev** [comment]
DisableDownloadTimeout is merged in master.

Anything else to close the issue?

**Comment by Neo-29** [comment]
Lo if don't think so 😀. Maybe adding ILoveCandy for fun 😉
