### ISSUE TITLE
Misconfiguration in function bootloader_systemd

### ISSUE THREAD

**Issue by fseatonuc** [picodotdev/alis#185]
The "default archlinux" line in the generated loader.conf is malformed.  It should be "default archlinux.conf".  

BTW, it might be nice to offer an option for this in case the user chose to install another kernel, like archlinux-lts.  Just a thought.

**Comment by picodotdev** [comment]
Fixed.

The default option is saved in each boot, so is not problem to choose other on first boot. The number of options could be customized is very high, to not implement all possibilities in alis the way is to choose sane defaults and if the user wants others he should tweak them after install. At the moment as guiding principle generally only major and common options is offered to configure in allis.
