### ISSUE TITLE
bwrap: pivot_root: Invalid argument

### ISSUE THREAD

**Issue by SudoSwole** [picodotdev/alis#195]
Hi pico, I get this error when I enable flatpaks and try enable Spotify for installation. Have you seen this before?

"bwrap: pivot_root: Invalid argument
Error while trying to apply extra data: apply_extra script failed, 
Error: failed to install com.Spotify.Client while trying to apply extra data"

**Comment by picodotdev** [comment]
Helo SudoSwole, same error in my test. Is this problem happening with any flatpak package or is a Spotify flatpak package issue? I see similar errors in the past with Sopotify.

https://github.com/flathub/com.spotify.Client/issues/178

**Comment by SudoSwole** [comment]
I tried clean installs with other flatpaks and had no issues. It seems the problem lies with the Spotify flatpak itself, nothing wrong with your script and also thank you for your hard work. It's appreciated!
