### ISSUE TITLE
When logging is on, prompts for passwords get out of order

### ISSUE THREAD

**Issue by fseatonuc** [picodotdev/alis#196]
I noticed that when I have logging enabled and I have passwords that are set to "ask", that the prompts don't always occur before the read executes.  I found two solutions for this:

1) replace the "read -sp" with an echo and a "read -s", or 2) the issue appears to be related to your two execs in the init_log function.  If you remove those two execs and replace them with a single exec, that also appears to resolve the issue:

           exec &> >(tee -a $FILE)

I also noticed the problem doesn't occur when I tested on a server with bash version 4, but it does on bash version 5.  Not exactly sure what's causing the problem, but perhaps this solution will help.

P.S. I noticed that you have a `set -o xtrace` in your init_log function in alis-commons.conf.   Was that added to help determine the cause of this issue?

**Comment by fseatonuc** [comment]
I noticed that when I have logging enabled and I have passwords that are set to "ask", that the prompts don't always occur before the read executes.  I found two solutions for this:

1) replace the "read -sp" with an echo and a "read -s", or 2) the issue appears to be related to your two execs in the init_log function.  If you remove those two execs and replace them with a single exec, that also appears to resolve the issue:

           exec &> >(tee -a $FILE)

I also noticed the problem doesn't occur when I tested on a server with bash version 4, but it does on bash version 5.  Not exactly sure what's causing the problem, but perhaps this solution will help.

P.S. I noticed that you have a `set -o xtrace` in your init_log function in alis-commons.conf.   Was that added to help determine the cause of this issue?

**Comment by picodotdev** [comment]
Gie a try to the fix. Use this command.

`exec > >(tee -a $FILE) 2> >(tee -a $FILE >&2)`

`set -o xtrace` is a way to output the commands that the script is executing. Useful combined with LOG to get a file with the output of the commands executed and also the commands executed.

**Comment by fseatonuc** [comment]
That didn't fix it for me.  Behaves exactly the same.  I should have mentioned that if you only have one set of passwords set to "ask", then this isn't an issue, assuming you don't make a mistake in the "retype" prompt for the password.  However, if your second entry for the password doesn't match the first, then the problem occurs.

Here's the output if I enter my root password incorrectly:

```
Type root password:
Retype root password: Type root password:
Root password don't match.  Please, type again.
```

Note how the second prompt for "Type root password:" came _before_ the "don't match" message.
