### ISSUE TITLE
Separate option for enabling/disabling xtrace in log_init function

### ISSUE THREAD

**Issue by fseatonuc** [picodotdev/alis#197]
I like the ability to LOG my install, but I'd like to have the option to turn the `set -o xtrace` in the `init_log` function off.  Would you consider adding a `DEBUG` option or something similar for controlling that behavior?

**Comment by picodotdev** [comment]
I added a new configuration variable.

https://github.com/picodotdev/alis/blob/469cbe2a7f7eced8dc35dc88253277d84a8223f6/alis.conf#L16
