### ISSUE TITLE
What is the variable 'LOG' used for?

### ISSUE THREAD

**Issue by fseatonuc** [picodotdev/alis#200]
https://github.com/picodotdev/alis/blob/0a9f1fb2f0ec3e7530ad9cf0ce1bcffe98551f22/alis-commons.conf#L49

I noticed that you changed LOG to LOG_FILE in most of the configuration files except for alis-commons.conf.  Was that intentional or was this reference just an oversight?

Thanks!

**Comment by picodotdev** [comment]
I missed that reference. I will review and probably change it to LOG_FILE.

**Comment by picodotdev** [comment]
Fixed
