### ISSUE TITLE
Trying to figure out where to add lines to the code to get sound working on laptop.

### ISSUE THREAD

**Issue by rathel** [picodotdev/alis#202]
Hello, I love this project by the way. I'm trying to figure how and where to add the following code(copied from my notes) so I can run it during the setup process for my sound to work instead of having to do it after the install process(which I forget, until I need sound working). Any guidance would be greatly appreciated.

```
echo "options snd-hda-intel dmic_detect=0" | sudo tee -a /etc/modprobe.d/alsa-base.conf
echo "blacklist snd_soc_skl" | sudo tee -a /etc/modprobe.d/blacklist.conf
```

**Comment by picodotdev** [comment]
Hello rathel, if you want to provision files on the system with alis you can place the archives on this directory [files](https://github.com/picodotdev/alis/tree/master/files) before start the installation. Currently, as example exist 99-killX.conf, if this does not applies to you delete it. All files on that directory will be provisioned mantaining directory structure.

The other necessary thing to do is enable the provision changing this variable value 
https://github.com/picodotdev/alis/blob/70baf049911f856ee862c1c2e06645575066db2d/alis.conf#L164.

**Comment by rathel** [comment]
@picodotdev Thank you, that's much easier than I was trying to think of.
