### ISSUE TITLE
`/boot` permissions set to `0755` is not good

### ISSUE THREAD

**Issue by tkna91** [picodotdev/alis#248]
I ran `bootctl install` to update the systemd-boot entry, resulting in the events in this thread.

- https://bbs.archlinux.org/viewtopic.php?id=287695
- https://bbs.archlinux.org/viewtopic.php?id=287790

If it seems that mounting `/boot` as follows before doing genfstab will generate an fstab with permission 0700 accordingly, it would be preferable to do so.
Sorry if I'm wrong.

```
mount -o uid=0,gid=0,fmask=0077,dmask=0077 "$DEVICE_BOOT" "${MNT_DIR}"/boot
```

**Comment by tkna91** [comment]
Is it this part here?
https://github.com/picodotdev/alis/blob/bc0738b0036409cf44239ceb85db82a461b25da2/alis-commons.sh#L423C38-L423C38

**Comment by code8buster** [comment]
These opts should only be used if the /boot partition is fat32 for EFI
Otherwise with bios + ext4 this fails.
