### ISSUE TITLE
Hangs on shell script

### ISSUE THREAD

**Issue by Zoleaf** [picodotdev/alis#250]
Script hangs after formatting the drives and downloading a 8.6GB file. 
It keeps repeating at message:

++ echo -e '\033[0;96m# install() step\033[0m'
# install() step
++ echo ''

++ COUNTRIES=()
++ local COUNTRIES
+++ systemctl is-active multi-user.target
++ '[' inactive == inactive ']'
++ sleep 1
+++ systemctl is-active multi-user.target
++ '[' inactive == inactive ']'
++ sleep 1
repeats

How can I solve this?
![shell script](https://github.com/picodotdev/alis/assets/159387787/72671049-e8fb-42fb-97be-5a943e184c05)

**Comment by picodotdev** [comment]
I will try to reproduce the problem and make a fix.

As a temporal fix you can remove this while loop.

https://github.com/picodotdev/alis/blob/251b037007a962596dfe44e0afce7cf50ded606a/alis.sh#L574

**Comment by picodotdev** [comment]
I did a test, not problems in it about this.

If you test again, the error persist in your machine?

**Comment by epichub** [comment]
I got this error too.

**Comment by picodotdev** [comment]
This error should dissapear.

Reverted 158784770ae893fd525c0d34a7e1e21d6dea50b9.
