### ISSUE TITLE
Wrong mount options for boot partition when BIOS_TYPE is bios

### ISSUE THREAD

**Issue by pjones** [picodotdev/alis#252]
If the `/sys/firmware/efi` directory doesn't exist then the `BIOS_TYPE` variable will be set to `"bios"`.  This results in the boot partition being formatted as ext4.  However, mounting the boot partition fails due to FAT32 options being passed to `mount`.

This is caused by the `PARTITION_OPTIONS_BOOT` variable being hard-coded to contain `uid`, `gid`, `fmask`, and `dmask` options, which are not valid ext4 options.

I would suggest setting `PARTITION_OPTIONS_BOOT` conditionally based on `BIOS_TYPE`.  A better option would be to not even use a boot partition when `BIOS_TYPE` is `bios`.

**Comment by picodotdev** [comment]
Thanks to note this.
