### ISSUE TITLE
Test with intel display driver

### ISSUE THREAD

**Issue by picodotdev** [picodotdev/alis#27]
Test alis with intel display drivers on intel graphics. Test KMS and hardware acceleration on bare metal.

Configure alis.conf and select intel driver:

DISPLAY_DRIVER="!intel !amdgpu !ati !nvidia !nvidia-lts !nvidia-390xx !nvidia-390xx-lts !nvidia-340xx !nvidia-340xx-lts !nouveau"

**Comment by theHari08** [comment]
Tested on HP Pavilion x360 dh1026tx, i7-10510U : works fine

**Comment by Anonymo** [comment]
On a T430, I installed Teamviewer and remoted in but the screen is laggy and glitching on the login screen and the taskbar disappears when I login.  using KDE.  Tried with Fedora and no issues.  Not sure if this is a iGPU issue/configuration or something else.  Suggestions welcome.
