### ISSUE TITLE
Test with NVMe device

### ISSUE THREAD

**Issue by picodotdev** [picodotdev/alis#36]
Test with NVMe device on bare metal

**Comment by theHari08** [comment]
Tested on HP Pavilion x360 dh1026tx, 16GiB ram, INTEL SSDPEKNW512G8H NVMe 512GiB: works fine

**Comment by kmanwar89** [comment]
Hi @picodotdev  - I have a new laptop I just bought which has an NVMe SSD. I'll test your script and let you know the outcome :)

Are there any particular tests you're looking to do? Something we should keep an eye out for?

**Comment by picodotdev** [comment]
Hello @kmanwar89, thank you, if you test the script let me know your system specs, brand, model, CPU, ... the graphics and wifi card are two aspects to test, I have tested with a intel graphics card if you have a amd or nvidia would be fine. Also, post your alis config, like system boot loader and desktop environment and file system type you have choosed and if you use encryption for the file system. Hope all work fine for you but if something does not work as expected let me know to be able do a fix.
