### ISSUE TITLE
Configuration only after manual initial install of Arch

### ISSUE THREAD

**Issue by khartahk** [picodotdev/alis#40]
Hi
I'd like to use [alez](https://github.com/danboid/ALEZ/) to setup the zfs for the filesystem which also installs base Arch without anything configured and then use your `alis` script to configure the system and install the packages you install.

What do you think would be the best approach to modify your script to support that?

I'm thinking I'd just add a variable that if `true` the partitioning and installing the base system of Arch would not be executed.

What do you think about this idea?

**Comment by picodotdev** [comment]
Seems possible but I would try to add to alis the ZFS support.

Is well supported Arch Linux installation on ZFS?
There is some guide in internet that shows the commans needed step by step ?
Is it necessary to use any AUR package?

**Comment by picodotdev** [comment]
Hi, this should be possible now, choosing `manual` for PARTITION_MODE variable and appropiate values for other PARTITION_* variables..
