### ISSUE TITLE
Allow multiple locales

### ISSUE THREAD

**Issue by iexos** [picodotdev/alis#63]
Thank you for this useful script :)

I am using locales

```
en_DK.UTF-8 UTF-8 for LC_TIME
en_US.UTF-8 UTF-8 in general
```

I can hack LC_TIME into LANG config variable:
```
LANG="LANG=en_US.UTF-8\nLC_TIME=en_DK.UTF-8"
```
but I cannot generate more than one locale

**Comment by picodotdev** [comment]
Do you really want to use many locales in the /etc/locale.gen file?

Seems something that can be changed once installed the system, feel free to send a pull request and I wiil review it.

**Comment by iexos** [comment]
> Seems something that can be changed once the system is installed.
Doesn't that go for anything? :)

I will make a pull request if I get around to it

**Comment by picodotdev** [comment]
There is not problem, only that this issue is a a bit corner case between a whislist and enhancement.

I will try to implement it anyway.

**Comment by picodotdev** [comment]
I have implemented a way to configure alis that I think covers your case. If you have some time give a try to it.

**Comment by iexos** [comment]
Thank you! :blush: :tada:

I will not be able to test it very soon, but I have already modified the config for the next time :)
