### ISSUE TITLE
Support Fastboot on Intel Graphics

### ISSUE THREAD

**Issue by picodotdev** [picodotdev/alis#67]
https://wiki.archlinux.org/index.php/Intel_graphics#Fastboot

**Comment by hixan** [comment]
It looks like it just needs
```
echo "options i915 fastboot=1" > /mnt/etc/modprobe.d/i915.conf
```
would this solve this?

**Comment by picodotdev** [comment]
Implemented but not tested. Thanks for the suggestion!.
