### ISSUE TITLE
Add subvolume setup for btrfs installs

### ISSUE THREAD

**Issue by bdarcus** [picodotdev/alis#68]
A number of distros (OpenSUSE and Fedora, for example) will configure btrfs subvolumes. Common seems to be separate subvolumes for /, /home, and /var.

**Comment by picodotdev** [comment]
https://wiki.archlinux.org/index.php/Btrfs#Subvolumes

Swap files are supported in btrfs since kernel 5.0, add support for this
https://wiki.archlinux.org/index.php/Btrfs#Swap_file

**Comment by bdarcus** [comment]
Here's a couple examples from the Arch world:

https://wiki.archlinux.org/index.php/User:Altercation/Bullet_Proof_Arch_Install
https://austinmorlan.com/posts/arch_linux_install/

**Comment by picodotdev** [comment]
I've just implemented this feature, the volumes created are: root, home, var and snapshots.

By the moment no swap in btrfs, currently seems there are some limitations for the swapfile.

If you have some time please give a try and comment in this issue if seems good to you, test in a virtual machine like VirtualBox.

**Comment by bdarcus** [comment]
Thanks!

I'm on Fedora, and for some reason, VirtualBox packaging is broken right now; something about broken dependencies. So I can't test with that ATM.

I can install on Gnome Boxes, and the script indicates success, but when I try to boot, it gets stuck and won't boot.

I have a new Dell laptop coming in, probably this week. I'll try installing fresh on that.

**Comment by bdarcus** [comment]
Just FYI, I haven't forgotten about this. Dell just appears to be severely
backlogged (maybe COVID-19 related?), so delivery taking much longer than
expected.

**Comment by bdarcus** [comment]
To come back to this, I did finally get the laptop, and ran into some errors trying to install using alis and gave up. It turned out to be a problem unrelated to arch or alis (how the nvme dirve was configure in the bios).

But I did subsequently try it on a Gnome Boxes VM, and it successfully installed and setup the appropriate BTRFS subvolumes.
