### ISSUE TITLE
/boot/loader/entries/archlinux.conf

### ISSUE THREAD

**Issue by RJGhugo** [picodotdev/alis#75]
add values to the file /boot/loader/entries/archlinux.conf
value="iommu=soft"

line expected: options initrd=initramfs-linux.img root=PARTUUID=ea8a2f82-b2e0-40cc-958c-d14dac083c19 rw  iommu=soft

**Comment by picodotdev** [comment]
Hi, I searched some information about iommu=soft kernel parameter but yet I dont know a lot about it and if it this parameter is different from no value or default.

Why this kernel parameter is necessary?
In wich use cases?
Is there some mention about it in the Arch Linux wiki?

**Comment by RJGhugo** [comment]
Hello, there is a problem with the AMD chip and virtualization. Deactivate IOMMU in UEFI/BIOS is done. But the "iommu=soft" would take care about this issue for sure.

https://askubuntu.com/questions/805008/errors-showing-while-booting-16-04-amd-vi-event-logged-io-page-fault

https://bbs.archlinux.org/viewtopic.php?id=224265

**Comment by picodotdev** [comment]
Is this necessary for all AMD systems ryzens also or only for old ones?
Are the intel systems affected by this in some way?
Is this the default for Intel systems?

**Comment by picodotdev** [comment]
Now with the new KERNELS_PARAMETERS configuration variable is possible to specify kernel parameters like "iommu=soft".
