### ISSUE TITLE
Keyboard Gnome

### ISSUE THREAD

**Issue by RJGhugo** [picodotdev/alis#77]
Hello, after installing there is no Swiss German keyboard in Gnome. Only US keyboard is activated.
The file /etc/X11/xorg.conf.d/00-keyboard.conf does not exists.
After switching via GUI the file is created automatically.
                 
```
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# instruct systemd-localed to update it.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "ch"
EndSection

```

**Comment by picodotdev** [comment]
Fixed

**Comment by picodotdev** [comment]
I have do not tested yet with a complete installation including gnome but now alis creates the /etc/X11/xorg.conf.d/00-keyboard.conf with the configured keyboard layout.

@RJGhugo, if you have some time you can test it and comment.
