### ISSUE TITLE
PARTITION_MODE environment variable must have a value

### ISSUE THREAD

**Issue by fralyx** [picodotdev/alis#80]
This happens only when I tried to run the installer on my MacBook Pro 14,1
But still works perfectly fine on windows PC. Can you support HFS+ later?

**Comment by picodotdev** [comment]
Which was your PARTITON_MODE value when you installed in your MacBook?
Why do you want use HFS+ instead ext4 in a Linux system?

**Comment by fralyx** [comment]
I use the ext4 already, but it just stops there, where do I set it or what is the value of the variable?

**Comment by picodotdev** [comment]
PARTITION_MODE possible values are auto custom or manual, one of them. The ! before means that that option is disabled/ignored.

What is the error when stops?

I dont tested it in a macbook and I dont read Mac's specific instructions https://wiki.archlinux.org/index.php/Mac so its is probable that something dont works.

**Comment by fralyx** [comment]
Exactly as the title says, but I solved it by using Manjaro minimal
