### ISSUE TITLE
MariaDB installation fails with a reason

### ISSUE THREAD

**Issue by solus-hq** [picodotdev/alis#85]
First of all, I'd like to thank @picodotdev for this absolutely amazing script saving lots of time!

But there's a small bug I'd like to report to make the project more stable:

I'm attaching a screenshot with error log, sorry but I can't copy this from my VirtualBox VM.

<img width="912" alt="Screenshot 2020-03-21 at 20 22 04" src="https://user-images.githubusercontent.com/26515805/77232451-fdd1f400-6bb1-11ea-9cc2-65ac9b7d1d15.png">

**Comment by picodotdev** [comment]
Seems not a alis problem, seems that someething happened when madriadb package was downloaded, the paackage is corrupt or a an error reading the madriadb package data from persistent storage. Can you try again?

**Comment by solus-hq** [comment]
Hello! Indeed it was some kind of network error. You can close this issue and sorry for a dumb issue.

<img width="912" alt="Screenshot 2020-03-24 at 17 32 26" src="https://user-images.githubusercontent.com/26515805/77437733-0ca8e880-6df6-11ea-920c-3fb463a36693.png">
