### ISSUE TITLE
Btrfs subvolumes?

### ISSUE THREAD

**Issue by InvisibleRasta** [picodotdev/alis#88]
how do you specify subvolumes for the install?

**Comment by picodotdev** [comment]
They are hardcoded.

https://github.com/picodotdev/alis/blob/c359ef46e6963b617d019f3f6663421d0f4accea/alis.sh#L490

What do you want o need?

**Comment by InvisibleRasta** [comment]
ah allright. i just saw it supported btrfs so i was wondering if you could add options to actually specify the subvolume names. for example i usually use the @ symbol for subvolumes, it makes it easier to recognize ... @root @home @var @snapshots

**Comment by picodotdev** [comment]
The @ symbol seems a convention adopted by many distros, I don't know enough to know what are the advantages and disadvantages of each option more than you said that are easier to recognice. I have not used btrfs to know its usefulness.

**Comment by InvisibleRasta** [comment]
bueno, muchas gracias. Buen trabajo con este script,me gusta!
