### ISSUE TITLE
System hangs on Reached target sound card

### ISSUE THREAD

**Issue by David-H-1** [picodotdev/alis#89]
I installed with LVM and then the system won't boot. It either hangs on Reached target sound card or mounting /boot

**Comment by picodotdev** [comment]
Can you share your alis.conf file and your computer spececifications?

**Comment by picodotdev** [comment]
Was the problem resolved?

**Comment by David-H-1** [comment]
No, I gave up and tried archfi instead

**Comment by picodotdev** [comment]
If you give me some information I will try to fix it if something does not works.

**Comment by Miosame** [comment]
@picodotdev just wanted to chime in, this isn't your scripts fault, this happens on raw arch, archfi, everywhere, it just randomly hangs on boot up and you have to reboot couple times for it to bust through to the login screen, in fact it's as old as 7 years by now: https://unix.stackexchange.com/questions/120634/why-does-my-arch-install-hang-at-random-stages-during-boot
