### ISSUE TITLE
curl failed to verify the legitimacy of the server ...

### ISSUE THREAD

**Issue by Schlunze** [picodotdev/alis#90]
sadly curl does not download the package with
`curl https://raw.githubusercontent.com/picodotdev/alis/master/download.sh | bash`
due to ssl cert problem.
The error message is:
curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it.
Greetings

**Comment by davidgonzalez-sh** [comment]
Is this error something temporal related to your internet connection?

**Comment by picodotdev** [comment]
Was this error something temporal related to your internet connection?
