### ISSUE TITLE
No wifi when wifi key contains space characters

### ISSUE THREAD

**Issue by Picea** [picodotdev/alis#92]
Hello,

I faced a problem with alis.sh when a wifi key contains spaces...

If the bash variable $WIFI_KEY in alis.conf contains space(s), the wifi will not function because no escape caracter(s) is written in /etc/netctl/wireless-wpa. For example, alis.sh would write a key line like this:
`Key=This is my passphrase`
instead of (c1) :
`Key=This\ is\ my\ passprase`
or (c2) :
`Key="This is my passphrase"`

I tried to manually escape every space in the $WIFI_KEY string but it did not work without editing alis.sh.

Finally, I did not escape the spaces in alis.conf and edit this line in alis.sh:
Instead of:
`sed -i 's/^Key=.*/Key='"$WIFI_KEY"'/' /etc/netctl/wireless-wpa`
I put:
`sed -i 's/^Key=.*/Key=\"'"$WIFI_KEY"'\"/' /etc/netctl/wireless-wpa`

Doing this allowed sed to write c2 line in /etc/netctl/wireless-wpa. 

Anyway, thanks a lot for the script; very useful and interesting to read...

**Comment by picodotdev** [comment]
Should be fixed. Thanks for the report and example code.
