### ISSUE TITLE
Add a model and variant in /etc/X11/xorg.conf.d/00-keyboard.conf

### ISSUE THREAD

**Issue by Picea** [picodotdev/alis#94]
Hi again,
I use swiss french keyboards so my KEYMAP and KEYLAYOUT are:
```
KEYMAP="KEYMAP=fr_CH"
KEYLAYOUT="ch"
```

However these 2 variables are not sufficient to write a correct keyboard configuration file for Xorg. Here is my actual keyboard conf for example (in` /etc/X11/xorg.conf.d/00-keyboard.conf ` ):

```
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "ch"
        Option "XkbModel" "pc105"
        Option "XkbVariant" "fr"
EndSection
```
Perhaps we could modify alis script and conf to take into account a model and a variant ?

**Comment by Picea** [comment]
Following my proposition, we could add 2 variables (that could remain empty if not needed). For example in alis.conf :
```
KEYMODEL="pc105" 
KEYVARIANT="fr"
```

Then, in alis.sh, line 615:
```
if [ -n "$KEYMODEL" ]; then
    sed -i 's/^EndSection/        Option "XkbModel" "'"$KEYMODEL"'"\nEndSection/' /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
fi

if [ -n "$KEYVARIANT" ]; then
    sed -i 's/^EndSection/        Option "XkbVariant" "'"$KEYVARIANT"'"\nEndSection/' /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
fi
```

**Comment by picodotdev** [comment]
Refer to https://wiki.archlinux.org/index.php/Xorg/Keyboard_configuration#Using_X_configuration_files for new variables
