### ISSUE TITLE
wget no longer on the official Arch Linux installation media

### ISSUE THREAD

**Issue by daubneyi** [picodotdev/alis#95]
As per [https://gitlab.archlinux.org/archlinux/archiso/-/commit/9b49621f78465cf912f853e1884e3f7446497229](url) wget is no longer on the official Arch Linux media.
![2020-07-19_13-01](https://user-images.githubusercontent.com/4220050/87866061-0e5b7500-c9c0-11ea-8dc9-01e510263b1a.png)

**Comment by daubneyi** [comment]
work around:
`curl -sL https://bit.ly/2F3CATp | sed -e 's/wget/curl -O/' | bash`

replacing `wget` to `curl -O` is probably the issue resolution.

**Comment by picodotdev** [comment]
Fixed. Thanks for the report.
