### ISSUE TITLE
Setting configuration for systemd-boot fails with error

### ISSUE THREAD

**Issue by daubneyi** [picodotdev/alis#96]
![2020-07-23_21-31](https://user-images.githubusercontent.com/4220050/88282146-5534cc00-cd2c-11ea-9c5e-e24df8d1b2d1.png)
Systemd-boot cannot be selected from the configuration file.  This fails with error
**BOOTLOADER environment variable value [systemd] must be in [grub]**

list of bootloaders not added to the test on ./alis.sh line 297.
As a result only grub works as the bootloader.

**Comment by daubneyi** [comment]
#97 

Referencing this pull request to fix the logic issue.

**Comment by picodotdev** [comment]
systemd-boot cannot be selected on a BIOS system, systemd-boot requires UEFI system. The only available bootloader for a BIOS system is grub.

Thats is the logic of the check.
