### ISSUE TITLE
cryptroot volume password?

### ISSUE THREAD

**Issue by BRENTGAMEZ** [picodotdev/alis#99]
keep getting a message saying: -
A password is required to access the cryptroot volume:
Enter passphrase for /dev/sda2:

but when I try my passwords or other suggestions from the internet I keep getting this message: -
No key available with this passphrase.
Enter passphrase for /dev/sda2:

???

**Comment by picodotdev** [comment]
The password unlock the cryptroot volume is configured with the variable ROOT_PASSWORD/ROOT_PASSWORD_RETYPE. Take in acount that if you use special characters or some characters that depend on keyboard layout you should set the keyboarld layout properly for your keyboard with the variables KEYMAP and KEYLAYOUT.
